### ISSUE TITLE
lib: deal with dh_with=python3 properly

### ISSUE THREAD

**Issue by cdluminate** [dupr/duprkit#45]
This is a bug in lib/. py3 and py2 should be separatly dealt with. Let me fix that with a regex. I should really do a py3-only packaging example in DefaultCollection along with the fix.

**Comment by paddatrapper** [comment]
I hope to have a python3 only example to add as a PR to the DefaultCollection once this bug is fixed

**Comment by cdluminate** [comment]
@paddatrapper See https://github.com/dupr/DefaultCollection/blob/master/tq/tq.durpkg for my pure-py3 example. (P.S. 0.0e has been released just now)
